sudo: required
language: python
services:
  - docker

jobs:
  include:
    - stage: lint
      script: 
        - pip install 'ansible-lint>=3.4.15'
        - ansible-lint tests/playbook.yml
    - stage: test
      script: 
        - pip install ${ANSIBLE} 'ansible-lint>=3.4.15' 'molecule==1.25.0' docker 'testinfra>=1.7.0,<=1.10.1' jmespath
        - molecule test
      env:
        - ANSIBLE='ansible>=2.3.0,<2.4.0' PROMETHEUS=1.8.2
        - ANSIBLE='ansible>=2.3.0,<2.4.0' PROMETHEUS=2.2.1
        - ANSIBLE='ansible>=2.4.0,<2.5.0' PROMETHEUS=1.8.2
        - ANSIBLE='ansible>=2.4.0,<2.5.0' PROMETHEUS=2.2.1
        - ANSIBLE='ansible>=2.5.0,<2.6.0' PROMETHEUS=1.8.2
        - ANSIBLE='ansible>=2.5.0,<2.6.0' PROMETHEUS=2.2.1
    - stage: deploy
      script: 
        - pip install docker git-semver
        - .travis/auto.sh

stages:
  - lint
  - test
  - name: deploy
    if: branch = master

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
